name: Test Commit
on:
  workflow_dispatch: {}
jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: print cwd
        run: echo "$PWD"
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
